# githubにgh-pagesブランチにpushがあった場合
# jobsの処理を行う ⇒ webページのデプロイ
name: Copy to Public

on:
  push:
    branches:
      - gh-pages
      
permissions:
  contents: write  # リポジトリのコンテンツに対する書き込み権限を付与
  
jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Copy files from src to public
        run: |
          mkdir -p public
          rm -r public/*
          cp -r src/* public/
          
      - name: Commit and push changes
        run: |
          git config --local user.name "masato-tsuji"
          git config --local user.email "masato_tsuji@mail.toyota.co.jp"
          git add public/
          git commit -m "Update public directory" || echo "No changes to commit"
          git push origin gh-pages
